name: Lint

on:
  pull_request:
  push:
    branches:
      - master
      - stable*

permissions:
  contents: read

jobs:
  php:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions: ['7.3', '7.4']
  
    name: php${{ matrix.php-versions }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up php ${{ matrix.php-versions }}
        uses: shivammathur/setup-php@v1
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none

      - name: Lint
        run: composer run lint

      - name: Download schema
        run: wget https://apps.nextcloud.com/schema/apps/info.xsd
      - name: Lint info.xml
        uses: ChristophWurst/xmllint-action@v1
        with:
          xml-file: ./appinfo/info.xml
          xml-schema-file: ./info.xsd

  php-cs-fixer:
    runs-on: ubuntu-latest

    name: php-cs check

    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Set up php
        uses: shivammathur/setup-php@master
        with:
          php-version: 7.4
          coverage: none
      - name: Install dependencies
        run: composer i
      - name: Run coding standards check
        run: composer run cs:check || ( echo 'Please run `composer run cs:fix` to format your code' && exit 1 )

  node:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-versions: [15, 16]

    name: node${{ matrix.node-versions }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up node ${{ matrix.node-versions }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-versions }}

      - name: Set up npm7
        run: npm i -g npm@7

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

  scss:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-versions: [15, 16]

    name: SCSS
    steps:
      - uses: actions/checkout@v2

      - name: Set up node ${{ matrix.node-versions }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-versions }}

      - name: Set up npm7
        run: npm i -g npm@7

      - name: Install dependencies
        run: npm ci

      - name: Lint SCSS
        run: npm run stylelint
